## **API**

# API are nothing but just data pipeline

In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=1e4f28753c1ecfb5591c9f690db68a20&language=en-US&page=1')

In [3]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 27.7246,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.712,
   'vote_count': 28513},
  {'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 27.4118,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.688,
   'vote_count': 21590},
  {'adult': False,
   'backdrop_path': '/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg',
   'genre_ids': [16, 14, 28, 35, 10402],
   'id': 803796,
   'original_language': 'en',
   'original_title': 'KPop Demon Hunters',
   'overview': "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
   'popularity': 243.7102,
   'poster_path': '/43c1efKzA1kigNzY0HBzeoXp8LR.jpg',
   'release_date': '2025-06-20',
   'title': 'KPop Demon Hunters',
   'video': False,
   'vote_average': 8.629,
   'vote_count': 460},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 15.2504,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.571,
   'vote_count': 13043},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 12.2727,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.565,
   'vote_count': 16520},
  {'adult': False,
   'backdrop_path': '/bxgTSUenZDHNFerQ1whRKplrMKF.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 15.3422,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.549,
   'vote_count': 9230},
  {'adult': False,
   'backdrop_path': '/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 16.7894,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.536,
   'vote_count': 17259},
  {'adult': False,
   'backdrop_path': '/enNubozHn9pXi0ycTVYUWfpHZm.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 23.865,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.521,
   'vote_count': 34033},
  {'adult': False,
   'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 7.3807,
   'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.518,
   'vote_count': 4494},
  {'adult': False,
   'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 15.8268,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.505,
   'vote_count': 18187},
  {'adult': False,
   'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 26.727,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 19206},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 19.1833,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.488,
   'vote_count': 28820},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 20.9935,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.487,
   'vote_count': 25213},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 16.236,
   'poster_path': '/8GJsy7w7frGquw1cy9jasOGNNI1.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.483,
   'vote_count': 11842},
  {'adult': False,
   'backdrop_path': '/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 26.1794,
   'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.468,
   'vote_count': 28352},
  {'adult': False,
   'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 18.3626,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-22',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.464,
   'vote_count': 9063},
  {'adult': False,
   'backdrop_path': '/l33oR0mnvf20avWyIMxW02EtQxn.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 33.1469,
   'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
   'release_date': '2014-11-05',
   'title': 'Interstellar',
   'video': False,
   'vote_average': 8.456,
   'vote_count': 37372},
  {'adult': False,
   'backdrop_path': '/7TF4p86ZafnxFuNqWdhpHXFO244.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 13.7457,
   'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.455,
   'vote_count': 13466},
  {'adult': False,
   'backdrop_path': '/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 6.84,
   'poster_path': '/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.455,
   'vote_count': 3925},
  {'adult': False,
   'backdrop_path': '/tDFvXn4tane9lUvFAFAUkMylwSr.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.0085,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.45,
   'vote_count': 5945}],
 'total_pages': 512,
 'total_results': 10225}

In [5]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,27.7246,8.712,28513
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,27.4118,8.688,21590
2,803796,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...",2025-06-20,243.7102,8.629,460
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,15.2504,8.571,13043
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,12.2727,8.565,16520
5,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,15.3422,8.549,9230
6,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,16.7894,8.536,17259
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,23.8650,8.521,34033
8,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,7.3807,8.518,4494
9,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,15.8268,8.505,18187
10,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,26.7270,8.500,19206
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,19.1833,8.488,28820
12,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,20.9935,8.487,25213
13,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,16.2360,8.483,11842
14,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,26.1794,8.468,28352
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-22,18.3626,8.464,9063
16,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,33.1469,8.456,37372
17,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,13.7457,8.455,13466
18,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,6.8400,8.455,3925
19,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0085,8.450,5945

In [7]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,27.7246,8.712,28513
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,27.4118,8.688,21590
2,803796,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...",2025-06-20,243.7102,8.629,460
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,15.2504,8.571,13043
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,12.2727,8.565,16520

In [8]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [27]:
import requests
import pandas as pd

df = pd.DataFrame()

for i in range(1, 429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=1e4f28753c1ecfb5591c9f690db68a20&language=en-US&page={}'.format(i))
    
    if response.status_code == 200:
        temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]
        df = pd.concat([df, temp_df], ignore_index=True)
    else:
        print(f"Failed to fetch page {i}: status code {response.status_code}")

# final DataFrame
print(df)

          id                     title  \
0        278  The Shawshank Redemption
1        238             The Godfather
2     803796        KPop Demon Hunters
3        240     The Godfather Part II
4        424          Schindler's List
...      ...                       ...
8555  862551                   Me Time
8556    9030                   The Eye
8557  395458                Suburbicon
8558  290555                    Wolves
8559   23514             The Rum Diary

                                               overview release_date  \
0     Imprisoned in the 1940s for the double murder ...   1994-09-23
1     Spanning the years 1945 to 1955, a chronicle o...   1972-03-14
2     When K-pop superstars Rumi, Mira and Zoey aren...   2025-06-20
3     In the continuing saga of the Corleone crime f...   1974-12-20
4     The true story of how businessman Oskar Schind...   1993-12-15
...                                                 ...          ...
8555  With his family away, a devoted stay-at-home d...   2022-08-26
8556  Violinist Sydney Wells was accidentally blinde...   2008-02-01
8557  In the quiet family town of Suburbicon during ...   2017-10-26
8558  The coming-of-age story of Cayden Richards. Fo...   2014-08-28
8559  Tired of the noise and madness of New York and...   2011-10-13

      popularity  vote_average  vote_count
0        27.7246         8.712       28513
1        27.4118         8.688       21590
2       243.7102         8.629         460
3        15.2504         8.571       13043
4        12.2727         8.565       16520
...          ...           ...         ...
8555      2.7359         5.887         943
8556      3.5263         5.887        1089
8557      2.4174         5.900        1743
8558      1.5703         5.886         307
8559      1.5036         5.886        1263

[8560 rows x 7 columns]

In [30]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,27.7246,8.712,28513
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,27.4118,8.688,21590
2,803796,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...",2025-06-20,243.7102,8.629,460
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,15.2504,8.571,13043
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,12.2727,8.565,16520
...,...,...,...,...,...,...,...
8555,862551,Me Time,"With his family away, a devoted stay-at-home d...",2022-08-26,2.7359,5.887,943
8556,9030,The Eye,Violinist Sydney Wells was accidentally blinde...,2008-02-01,3.5263,5.887,1089
8557,395458,Suburbicon,In the quiet family town of Suburbicon during ...,2017-10-26,2.4174,5.900,1743
8558,290555,Wolves,The coming-of-age story of Cayden Richards. Fo...,2014-08-28,1.5703,5.886,307
8559,23514,The Rum Diary,Tired of the noise and madness of New York and...,2011-10-13,1.5036,5.886,1263

In [31]:
df.shape

(8560, 7)

In [32]:
df.to_csv('movies.csv')